import axios from "axios";

const TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJpYW12aWppdGFzaHZhQGdtYWlsLmNvbSIsImV4cCI6MTc4MTE2OTc5NCwiaWF0IjoxNzgxMTY4ODk0LCJpc3MiOiJBZmZvcmQgTWVkaWNhbCBUZWNobm9sb2dpZXMgUHJpdmF0ZSBMaW1pdGVkIiwianRpIjoiNTk1Y2VkYWMtYzdjOS00NDhhLTgzNDItZjZiYjBkZTQzMDk2IiwibG9jYWxlIjoiZW4tSU4iLCJuYW1lIjoidmlqaXRhc2h2YSBuYXJheWFuIHBhbmRleSIsInN1YiI6IjFhMzJhYjBlLTUzMTYtNGNiNC1hYjkyLTExMDliNmZmOTMwNyJ9LCJlbWFpbCI6ImlhbXZpaml0YXNodmFAZ21haWwuY29tIiwibmFtZSI6InZpaml0YXNodmEgbmFyYXlhbiBwYW5kZXkiLCJyb2xsTm8iOiIyMzAwNDYxNTQwMTAzIiwiYWNjZXNzQ29kZSI6IkJBVkRTaCIsImNsaWVudElEIjoiMWEzMmFiMGUtNTMxNi00Y2I0LWFiOTItMTEwOWI2ZmY5MzA3IiwiY2xpZW50U2VjcmV0IjoiQm5KcGtZcnlkUVhZalRjaiJ9.FbisWG7_OwbZKZ7p6WNmJO98MrzOXF3FtzKH4vKjPdw";

export const fetchNotifications=async()=>{

const res=await axios.get(
"http://4.224.186.213/evaluation-service/notifications",
{
headers:{
Authorization:`Bearer ${TOKEN}`
}
}
);

return res.data.notifications;
};